name = "dockerhub-proxy"
main = "_worker.js"  # 或您的入口文件路径
compatibility_date = "2025-12-02"

[vars]
DOCKERHUB_USERNAME = "boyika001"
DOCKERHUB_PASSWORD = "Hn3#2@1!"

# 配置更长的超时时间
[triggers]
timeout = 300
